---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/privileged
resources:
  - ./external-dns/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./external-routes/ks.yaml
  - ./multus/ks.yaml
