lxc:
  hosts:
    reap:
      ansible_host: reap
    chicken:
      ansible_host: chicken
    beholder:
      ansible_host: beholder
    salamander:
      ansible_host: salamander
    # fish:
    #   ansible_host: fish

suse:
  hosts:
    KIPP:
      ansible_host: 10.10.0.160
      # ansible_host: KIPP
      ansible_user: suse
    sculpin:
      ansible_host: sculpin

debian:
  children:
    lxc:
    academy:
