---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: chancey.dev
    target: _self
    background:
      image: https://i.imgur.com/NdsEGXR.png
      blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 30 # 0-100
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github | stacks:
            - abbr: GH
              href: https://github.com/jonathanchancey/stacks
        - Claude:
            - abbr: CL
              href: https://claude.ai/chats/
        - Google Cloud:
            - abbr: GCP
              href: https://console.cloud.google.com/
    - Personal:
        - Email:
            - abbr: PR
              href: https://mail.proton.me/u/0/inbox
        - Calendar:
            - abbr: CAL
              href: https://calendar.proton.me/u/0
        - Kagi:
            - abbr: K
              href: https://kagi.com/
        - Wanikani:
            - abbr: Wa
              href: https://wanikani.com/dashboard
        - Monarch:
            - abbr: Mo
              href: https://monarch.com/dashboard
        - Spotify:
            - abbr: Mo
              href: https://spotify.com/
    - Professional:
        - Google Drive:
            - abbr: DOC
              href: https://drive.google.com/drive/u/0/home
        - Prusa Connect:
            - abbr: PRU
              href: https://connect.prusa3d.com
        - Onshape:
            - abbr: ONS
              href: https://cad.onshape.com/documents
  services.yaml: |
    - Management:
      - Proxmox:
          href: https://proxmox.chancey.dev
          icon: proxmox.png
          description: Hypervisor
      - TrueNAS:
          href: https://vents.chancey.dev
          icon: si-truenas-#0095D5
          description: Baremetal NAS
      - Kanidm:
          href: https://idm.chancey.dev/
          icon: kanidm.png
          description: Identity Provider
      - ZITADEL:
          href: https://auth.chancey.dev/
          icon: zitadel.png
          description: Identity Provider
      - Home Assistant:
          href: https://home-assistant.chancey.dev
          icon: home-assistant.png
          description: Home Automation
      - Kopia:
          href: https://kopia.chancey.dev/
          icon: si-kubernetes-#326CE5
          description: PVC Backup
    - Monitoring:
      - Grafana:
          href: https://grafana.bastille.chancey.dev/
          icon: grafana.png
          description: Observability Platform
      - Gatus:
          href: https://status.chancey.dev/
          icon: mdi-gate-#3cad4b
          description: Status
      - Prometheus:
          href: https://prometheus.chancey.dev/
          icon: prometheus.png
          description: Time Series Database
    - Network:
      - Unifi Dream Machine:
          href: https://intrepid.chancey.dev
          icon: unifi.png
          description: Unforbidden Router
      - 24p PoE Switch:
          href: https://sw-01.chancey.dev/?
          icon: si-mikrotik-#CCCCCC
          description: 24p PoE Mikrotik Switch
      - 8p 2.5Gb Switch:
          href: https://sw-02.chancey.dev/?
          icon: si-mikrotik-#CCCCCC
          description: 2.5Gb Mikrotik Switch
      - 24p Switch:
          href: https://sw-03.chancey.dev/index.html
          icon: si-mikrotik-#CCCCCC
          description: 24p Mikrotik Switch
      - Nginx:
          href: https://nginx.vents.chancey.dev/
          icon: nginx.png
          description: Decoupled Reverse Proxy
    - Media:
      - Immich:
          href: https://photos.chancey.dev/
          icon: immich.png
          description: Photo Collection Manager
      - Garage:
          href: https://garage.vents.chancey.dev/
          icon: garage.png
          description: S3 storage
      - Jellyfin:
          href: https://jellyfin.chancey.dev/
          icon: jellyfin.png
          description: Media Server
      - Navidrome:
          href: https://navidrome.chancey.dev/
          icon: navidrome.png
          description: Music Collection Manager
      - Filebrowser:
          href: https://filebrowser.chancey.dev/
          icon: filebrowser.png
          description: Music Collection Manager
      - Gitea:
          href: https://gitea.chancey.dev/
          icon: gitea.png
          description: Version Control
      - Miniflux:
          href: https://miniflux.chancey.dev/
          icon: miniflux.png
          description: RSS Reader

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: custom
        url: https://kagi.com/search?q=
        target: _blank
        suggestionUrl: https://kagi.com/api/autosuggest?q= # Optional
        showSearchSuggestions: true # Optional
  docker.yaml: ""
