---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sw-01.yaml
  - sw-02.yaml
  - sw-03.yaml
  - proxmox.yaml
  - certificates/proxmox.yaml
