---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - certificate.yaml
  - pvc.yaml
configMapGenerator:
  - name: kanidm-configmap
    files:
      - config.toml=resources/config.toml
    options:
      disableNameSuffixHash: true
